### ISSUE TITLE
Server-side peculiarities

### ISSUE THREAD

**Issue by zamber** [ireade/wtfoperamini#1]
Hi,

Some (if not most) of discrepancies detailed will be impossible to fix, ["due to the peculiarities of server-side rendering and limited client capabilities"](https://dev.opera.com/articles/browsers-modes-engines/). IMHO these should have a category of it's own or have a emoji indicator that it's impossible to fix.

Cheers.

**Comment by ireade** [comment]
Hi @zamber ,

You're totally right about this. There are some features that can't or don't need a workaround. I'll work on tagging them so they can be filtered out. 

Thanks!

**Comment by zamber** [comment]
:+1:
